#	THIS FILE IS GENERATED BY AI, I DIDNT WRITE IT AND DO NOT KNOW HOW TO WRITE IT.
#	IT IS PROBERLT THE ONLY FILE AI GENERATED IN THIS PROJECT
# ==========================================
# CHIP-8 Emulator Makefile
# ==========================================


# 1. Compiler and Flags
CXX      = g++
# Added -fno-omit-frame-pointer for better backtraces
CXXFLAGS = -std=c++17 -Wall -Wextra -Werror -Iinclude -g
# AddressSanitizer flags
DEBUG_FLAGS = -fsanitize=address -fno-omit-frame-pointer
LDFLAGS  = -lncursesw

# 2. Target Name
TARGET   = chip8_emu

# 3. Directories
SRCDIR   = src
INCDIR   = include
OBJDIR   = obj

# 4. Source and Object Files
SRCS     = $(wildcard $(SRCDIR)/*.cpp)
OBJS     = $(SRCS:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)

# 5. Primary Rules
all: $(TARGET)

# Standard build
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# --- DEBUG TARGET ---
# Use this to catch the Segfault. 
# It adds ASan to both compilation and linking.
debug: CXXFLAGS += $(DEBUG_FLAGS)
debug: LDFLAGS += -fsanitize=address
debug: rebuild
	@echo "--- Debug build with AddressSanitizer complete ---"

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

# 6. Utility Rules
clean:
	rm -rf $(OBJDIR) $(TARGET)
	@echo "Cleaned up object files and executable."

rebuild: clean all

.PHONY: all clean rebuild debug