#	THIS FILE IS GENERATED BY AI, I DIDNT WRITE IT AND DO NOT KNOW HOW TO WRITE IT.
#	IT IS PROBERLT THE ONLY FILE AI GENERATED IN THIS PROJECT
# ==========================================
# CHIP-8 Emulator Makefile
# ==========================================

# 1. Compiler and Flags
CXX      = g++
# -Iinclude tells the compiler where to find your .h files
# -g adds debug symbols for GDB
CXXFLAGS = -std=c++17 -Wall -Wextra -Werror -Iinclude -g
# -lncurses must be linked at the end to resolve noecho/wrefresh
LDFLAGS  = -lncursesw

# 2. Target Name
TARGET   = chip8_emu

# 3. Directories
SRCDIR   = src
INCDIR   = include
OBJDIR   = obj

# 4. Source and Object Files
# Automatically finds all .cpp files in src/
SRCS     = $(wildcard $(SRCDIR)/*.cpp)
# Maps src/filename.cpp to obj/filename.o
OBJS     = $(SRCS:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)

# 5. Primary Rules
all: $(TARGET)

# Linking: The order of $(LDFLAGS) at the end is vital for ncurses
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# Compilation: Compiles each .cpp into a .o file inside the obj/ folder
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Create the object directory if it doesn't exist
$(OBJDIR):
	mkdir -p $(OBJDIR)

# 6. Utility Rules
clean:
	rm -rf $(OBJDIR) $(TARGET)
	@echo "Cleaned up object files and executable."

# Performs a full clean and then builds from scratch
rebuild: clean all

.PHONY: all clean rebuild