#	THIS FILE IS GENERATED BY AI, I DIDNT WRITE IT AND DO NOT KNOW HOW TO WRITE IT.
#	IT IS PROBERLT THE ONLY FILE AI GENERATED IN THIS PROJECT, I DONT KNOW HOW TO USE MAKEFILE.

# 1. Compiler and Flags
CXX      = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -Werror -O3
LDFLAGS  = -lncursesw

# 2. Project Structure
TARGET   = chip8_emu
SRCS     = $(wildcard *.cpp)
OBJS     = $(SRCS:.cpp=.o)

# 3. Default Rule (The one that runs when you just type 'make')
all: $(TARGET)

# 4. Linking the final executable
$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $(TARGET) $(LDFLAGS)

# 5. Compiling individual source files into object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# 6. Utility Rules
clean:
	rm -f $(OBJS) $(TARGET)

rebuild: clean all

.PHONY: all clean rebuild